<?php

use Drupal\node\NodeInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;
use Drupal\bhcc_events_plus\EventsExtraFieldDisplay;

/**
 * Implements hook_theme().
 */
function bhcc_events_plus_theme() {
  return [
    'bhcc_events_facets' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Implements hook_views_data_alter().
 */
function bhcc_events_plus_views_data_alter(array &$data) {
  $data['node_field_data']['bhcc_localgov_facets'] = [
    'title' => t('Event Facets'),
    'filter' => array(
      'label' => t('Event Facets'),
      'field' => 'localgov_directory_facets_select',
      'id' => 'bhcc_localgov_facets'
    )
  ];
}

/**
 * Implements hook_entity_extra_field_info().
 */
function bhcc_events_plus_entity_extra_field_info() {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EventsExtraFieldDisplay::class)
    ->entityExtraFieldInfo();
}

/**
 * Implements hook_ENTITY_TYPE_view().
 */
function bhcc_events_plus_node_view(array &$build, NodeInterface $node, EntityViewDisplayInterface $display, $view_mode) {
  return \Drupal::service('class_resolver')
    ->getInstanceFromDefinition(EventsExtraFieldDisplay::class)
    ->nodeView($build, $node, $display, $view_mode);
}
